ame: Docker build and push

on:
  push:
    branches:
      - 'main'  # change this to your working branch

env:
  USE_GHCR: '0'  # Set USE_GHCR environment variable
  PLATFORMS: 'linux/amd64'  # Set your desired platform

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: ${{ env.USE_GHCR != '1' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        if: ${{ env.USE_GHCR != '1' }}
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ github.actor }}/puppeteer-recording
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      - name: Log into ghcr
        uses: docker/login-action@v1
        if: ${{ env.USE_GHCR == '1' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to ghcr
        uses: docker/build-push-action@v2
        if: ${{ env.USE_GHCR == '1' }}
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ghcr.io/${{ github.actor }}/puppeteer-recording
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max